apiVersion: v1
kind: Service
metadata:
  name: app-service

spec:
  # this defines which pods are going to be represented by this service
  # the service becomes a network endpoint for either other services
  # or maybe external users to connect to (e.g. broswer)
  selector:
    mylabel: web-app
    release: '0-5'
  ports:
    - name: http
      port: 80
      # why NodePort?
      # to access it quickly outside of the IP node
      nodePort: 30080

  type: NodePort
    