# image with tag release0

apiVersion: v1
kind: Pod
metadata:
  name: web-app.0
  labels:
    # mylabel here is an arbitrary name
    # this is used to talk to the service's selector
    mylabel: web-app
    release: '0'
spec:
  containers:
  - name: web-app
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
# image with tag release0-5

apiVersion: v1
kind: Pod
metadata:
  name: web-app.0-5
  labels:
    # mylabel here is an arbitrary name
    # this is used to talk to the service's selector
    mylabel: web-app
    release: '0-5'
spec:
  containers:
  - name: web-app
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

